### ISSUE TITLE
After Games you don't lose items

### ISSUE THREAD

**Issue by EmeraldDragonGamer** [LeronDoesGM/ParadiseCraft-Bug-Reports#6]
#### Description
 I wouldn't call this a huge bug but when players play in pvp games and they win, they keep their items once sent back to spawn. Also pvp is on at spawn so players can kill each other.

**Comment by Shavinda101** [comment]
This issue was resolved. If, the player opens their inventory and closes it the items will go away. If, the player just runs around the items will go away. If, the player tries to use the item in the spawn the items will disappear. Thank you for reporting still. Closing issue.
